image: registry.gitlab.com/andreyunderoak/tape_sort

stages:
  - build
  - test
  - build-docker
  - push

variables:
  BUILD_DIR: build

before_script:
  - mkdir -p $BUILD_DIR
  - cd $BUILD_DIR
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - cd build
    - cmake ..
    - make -j$(($(nproc)-1))        

test:
  stage: test
  dependencies:
    - build                          
  script:
    - cd build
    - ctest --output-on-failure       
  
build-docker:
  stage: build-docker
  dependencies:
    - build
  script:
    - docker build -t "$CI_REGISTRY_IMAGE:build-temp" -f docker/Dockerfile .
  rules:
    - if: $CI_COMMIT_BRANCH == "release"

push:
  stage: push
  dependencies:
    - build-docker
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
    - docker tag "$CI_REGISTRY_IMAGE:build-temp" "$CI_REGISTRY_IMAGE:latest"  
    - docker push "$CI_REGISTRY_IMAGE:latest"                                
    - docker rmi "$CI_REGISTRY_IMAGE:build-temp"              
  rules:
    - if: $CI_COMMIT_BRANCH == "release"               
