image: registry.gitlab.com/andreyunderoak/tape_sort:latest

stages:
  - test
  - push   

before_script:
  - chmod +x -R scripts    

test:
  stage: test                 
  script:
    - sh scripts/build.sh
    - sh scripts/test.sh      

push:
  stage: push
  dependencies:
    - build-docker
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - sh scripts/docker_build.sh
    - docker push registry.gitlab.com/andreyunderoak/tape_sort                                         
  rules:
    - if: $CI_COMMIT_BRANCH == "release"               
