image: registry.gitlab.com/andreyunderoak/tape_sort:latest

stages:
  - test

before_script:
  - chmod +x -R scripts    

test:
  stage: test                 
  script:
    - sh scripts/build.sh
    - sh scripts/test.sh                
