name: Build
on:
  push:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.0

      - name: Configure and Build Project
        uses: threeal/cmake-action@v1.3.0
        with:
          run-build: true
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifact
          path: ${{ steps.build.outputs.build-dir }}/${{ github.event.repository.name }}
      # - name: Test Project
      #   uses: threeal/ctest-action@v1.1.0
